### ISSUE TITLE
能成功签到，但是无法通过telegram发送通知

### ISSUE THREAD

**Issue by ShulingTang** [GamerNoTitle/wyycg-autocheckin#25]
Run python3 main.py "***" "***" "***" "" "" ""
[网易云游戏自动签到]脚本运行错误，具体请参见日志！
检测到2个账号，即将开始签到！
Traceback (most recent call last):
  File "main.py", line 185, in <module>
    send(teleid, teleinfomsg)
  File "main.py", line 82, in send
    bot.sendMessage(id, message, parse_mode=None, disable_web_page_preview=None, disable_notification=None,
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/telepot/__init__.py", line 513, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: chat not found', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'})
Error: Process completed with exit code 1.

**Comment by GamerNoTitle** [comment]
请参照https://github.com/GamerNoTitle/wyycg-autocheckin#chat-not-found
