### ISSUE TITLE
签到失败显示401

### ISSUE THREAD

**Issue by zhul3762** [GamerNoTitle/wyycg-autocheckin#28]
Run python3 main.py "***" "***" "***   " "" "" ""
  python3 main.py "***" "***" "***   " "" "" ""
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.9/x64
Traceback (most recent call last):
  File "main.py", line 185, in <module>
    send(teleid, teleinfomsg)
  File "main.py", line 82, in send
    bot.sendMessage(id, message, parse_mode=None, disable_web_page_preview=None, disable_notification=None,
  File "/opt/hostedtoolcache/Python/3.8.9/x64/lib/python3.8/site-packages/telepot/__init__.py", line 513, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/opt/hostedtoolcache/Python/3.8.9/x64/lib/python3.8/site-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.9/x64/lib/python3.8/site-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/opt/hostedtoolcache/Python/3.8.9/x64/lib/python3.8/site-packages/telepot/api.py", line 147, in _parse
    raise e(description, error_code, data)
telepot.exception.UnauthorizedError: ('Unauthorized', 401, {'ok': False, 'error_code': 401, 'description': 'Unauthorized'})
[网易云游戏自动签到]脚本运行错误，具体请参见日志！
检测到2个账号，即将开始签到！
Error: Process completed with exit code 1.

我试了重新设置teleid和teletoken也不行

**Comment by GamerNoTitle** [comment]
你的teletoken后面为什么还要带空格……
把teletoken重新填一下 你的bot的token认证失败了
我猜是你后面的空格的问题

**Comment by GamerNoTitle** [comment]
![image](https://user-images.githubusercontent.com/28426291/116637433-84046080-a996-11eb-88a5-322a57f9b667.png)

**Comment by zhul3762** [comment]
![image](https://user-images.githubusercontent.com/80536869/116775195-4dad0b00-aa94-11eb-8aba-cb42728ed28f.png)
重新试了 没有空格啊 还有不行呢

**Comment by zhul3762** [comment]
好像可以了 现在返回400了 应该是成功了吧 明天在看看

**Comment by zhul3762** [comment]
![image](https://user-images.githubusercontent.com/80536869/116775374-57833e00-aa95-11eb-8ef8-13cf0cbdf07d.png)
dj'u但是电报没有收到推送

**Comment by GamerNoTitle** [comment]
嗯 你明天再看看能不能收到推送
400是因为你今天签到过了

**Comment by leechuy** [comment]
可以了 现在签到成功了 推送也是 非常感谢
